name: Generate Tests

on:
  merge_request:
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gocodeo
      run: pip install gocodeo==0.0.13

    - name: Set up authentication key
      run: echo "${{ secrets.secret }}" > gocodeo_key.txt

    - name: Generate tests
      run: gocodeo-generate generate src/accordion/accordion.module.ts < gocodeo_key.txt
