name: Generate Tests

on:
  pull_request:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gocodeo
      run: pip install gocodeo==0.0.13

    - name: Run the package with secret
      run: |
        echo "${{ secrets.secret }}" | gocodeo-generate generate src/accordion/accordion.module.ts

    - name: Commit and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --local user.email "soumendraroman@gmail.com"
        git config --local user.name "Soumendraprasad"
        git add src/accordion/gocodeo_tests/
        git commit -m "Generate tests using gocodeo"
        git push origin main
    - name: Executing the generated test cases
      run: npm run test-lib
