name: Generate Tests

on:
  push:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gocodeo
      run: pip install gocodeo==0.0.12

    - name: Run the package with secret
      run: |
        echo "${{ secrets.secret }}" | gocodeo-generate generate src/accordion/accordion.module.ts

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate tests using gocodeo"
        commit_options: "--no-verify"
        branch: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
