name: Generate Tests

on:
  push:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gocodeo
      run: pip install -i https://test.pypi.org/simple/ gocodeo==0.0.12

    - name: Run the package with secret
      run: |
        echo "${{ secrets.secret }}" | gocodeo-generate generate src/accordion/accordion.module.ts
      env:
        secret: ${{ secrets.secret }}
