name: Print Secret

on:
  push:
    branches: [main]

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print Secret Key
      run: pip install gocodeo==0.0.13
     - name: List Folders
      run: |
        cd Soumendraprasad/ng-bootstrap
        ls -d */ > folders.txt
        cat folders.txt

      
