name: Print Secret

on:
  push:
    branches: [main]

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print Secret Key
      run: pip install gocodeo==0.0.13
    - name: Run the package
      run: gocodeo-generate generate src/accordion/accordion.module.ts
      
