name: List Folders

on:
  push:
    branches: [main]

jobs:
  list-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List Folders in src/accordion
      run: |
        ls -d src/accordion/*/ | sed 's#src/accordion/##' > accordion_folders.txt
        cat accordion_folders.txt
